### ISSUE TITLE
Significant performance boost with disabled angularJS debug data

### ISSUE THREAD

**Issue by oliver-p** [w11k/fabs#38]
Since angularJS 1.3 there is an option that gives a significant performance boost by disabling the angularJS debug data.
https://docs.angularjs.org/guide/production

FABS shall provide an option to disable this feature and may disable it per default in "dist" target.

**Comment by pburgmer** [comment]
will be released as 0.12.0 soon

you can use a snippet like this one
```
// @if target == 'compile'
angular.module('app').config(/* @ngInject */ function ($compileProvider) {
  $compileProvider.debugInfoEnabled(false);
});
// @endif
```
